spring:
  main:
    web-application-type: REACTIVE
  application:
    name: gateway-service
  # cloud:
  #   gateway:
  #     routes:
  #     - id: admin-service
  #       uri: http://localhost:9000
  #       predicates:
  #         - Path=/api/v1/**
  #       filters:
     

server:
    port: 8000

logging:
  level:
    root: INFO
    '[org.springframework]' : INFO
    '[org.aston.ems]' : DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
    
