spring:
  main:
    web-application-type: REACTIVE
  application:
    name: gateway-service
  cloud:
   gateway:
     routes:
     - id: admin-service
       uri: http://admin-service:9000
       predicates:
         - Path=/admin/**
       filters:
          - StripPrefix=1

server:
    port: 8000

logging:
  level:
    root: INFO
    '[org.springframework]' : INFO
    '[org.springframework.cloud]' : INFO
    '[org.aston.ems]' : DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
    
