spring:
#  sql:
#    init:
#      mode: always
  application:
    name: admin-service
  datasource:
    username: max
    password: pas
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://admin-db:5432/ems
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.yml
  jpa:
#    defer-datasource-initialization: true
#    open-in-view: false
    show-sql: true
    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none

server:
    port: 9000

logging:
  level:
    root: INFO
    '[org.springframework]' : INFO
    '[org.aston.ems]' : DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8000/eureka



springdoc:
  swagger-ui:
    path: '/swagger.html'
