spring:
  application:
    name: admin_service

server:
    port: 9000

logging:
  level:
    root: INFO
    '[org.springframework]' : INFO
    '[org.aston.ems]' : DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
    
